repositories:
  - name: stable
    url: https://charts.helm.sh/stable
  - name: incubator
    url: https://charts.helm.sh/incubator
  - name: metrics-server
    url: https://kubernetes-sigs.github.io/metrics-server/
  - name: kubernetes-dashboard
    url: https://kubernetes.github.io/dashboard/
environments:
  {{ .Environment.Name }}:
#helmfiles:
#  - path: ./aws-alb-ingress-controller
#  - path: ./cluster-autoscaler
releases:
  - name: metrics-server
    version: 3.8.2
    namespace: kube-system
    chart: metrics-server/metrics-server
    values:
      - ./metrics-server/values.yaml
  - name: kubernetes-dashboard
    version: 5.3.1
    namespace: kubernetes-dashboard
    chart: kubernetes-dashboard/kubernetes-dashboard
    values:
      - ./kubernetes-dashboard/values.yaml
