apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "adceet-write-api-server.fullname" . }}
  labels:
    {{- include "adceet-write-api-server.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "adceet-write-api-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "adceet-write-api-server.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "adceet-write-api-server.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort.http }}
              protocol: TCP
            - name: management
              containerPort: {{ .Values.containerPort.management }}
              protocol: TCP
            - name: remoting
              containerPort: {{ .Values.containerPort.akkaRemoting }}
              protocol: TCP
            - name: kamon
              containerPort: {{ .Values.containerPort.kamon }}
              protocol: TCP
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP

            - name: KAMON_ENVIRONMENT_TAGS_ENV_NAME
              value: {{ .Values.envName | quote }}
            - name: KAMON_ENVIRONMENT_TAGS_PREFIX
              value: {{ .Values.prefix | quote }}
            - name: AWS_REGION
              value: {{ .Values.awsRegion | quote }}
            - name: AWS_STS_REGIONAL_ENDPOINTS
              value: {{ .Values.awsStsRegionalEndpoints | quote }}

            - name: ENV_NAME
              value: {{ .Values.envName | quote }}
            - name: CONFIG_RESOURCE
              value: {{ .Values.configResource | quote }}

            - name: JVM_HEAP_MIN
              value: {{ .Values.jvmHeapMin | quote }}
            - name: JVM_HEAP_MAX
              value: {{ .Values.jvmHeapMax | quote }}
            - name: JVM_META_MAX
              value: {{ .Values.jvmMetaMax | quote }}


          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
