localstack:
  enabled: true
  resources:
    limits:
      cpu: "1"
      memory: "1000Mi"
    requests:
      cpu: "0.5"
      memory: "500Mi"
regcred:
  enabled: false
  server:
  username:
  password:
ecrCred:
  enabled: false
  server: 234188972441.dkr.ecr.us-east-1.amazonaws.com
  password:
writeApi:
  akkaClusterName: write-api
  env:
    - name: "AWS_REGION"
      value: "us-east-1"
    - name: "ROOT_LOG_LEVEL"
      value: "INFO"
    - name: "CONFIG_FORCE_akka_discovery_kubernetes__api_pod__namespace"
      value: "adceet"
    - name: "CONFIG_FORCE_akka_discovery_kubernetes__api_pod__label__selector"
      value: "adceet/akka-cluster-name=write-api"
    - name: "CONFIG_FORCE_akka_discovery_kubernetes__api_pod__port__name"
      value: "management"
    - name: "CONFIG_FORCE_akka_remote_artery_canonical_port"
      value: "25520"
    - name: "CONFIG_FORCE_kamon_environment_tags_env"
      value: "om2eep1k-addceet"
    - name: "CONFIG_FORCE_kamon_datadog_agent_hostname"
      value: "datadog-agent.kube-system"
  # Write API Server
  writeApiServer:
    datadog:
      logs:
        enabled: false
    frontend:
      enabled: true
      version: 0.2.8
      image:
        repository: 234188972441.dkr.ecr.us-east-1.amazonaws.com/om2eep1k-ecr-adceet-write-api-server-scala
        tag: dev-d3df642aea3a1f9c4052d095807b0273d20b3097-1661487120398
        pullPolicy: IfNotPresent
      resources:
        limits:
          cpu: "1"
          memory: "2Gi"
        requests:
          cpu: "0.5"
          memory: "1Gi"
      service:
        type: ClusterIP
        port: 8081
        nodePort: 30031
      replicaCount: 2
      autoscaling:
        enabled: false
      processTimeoutInSec: 10
      hostname: j5ik2o-write-api.us-east-1.sandbox-sagrada.cwtest.info
      externalDNS:
        awsWeight: 100
      serviceAccount:
        create: true
        name: write-api-server-frontend-akka
      command:
        - /opt/docker/bin/adceet-write-api-server-scala
        - -Dconfig.resource=application-cluster-frontend.conf
        - -Dconfig.override_with_env_vars=true
      env:
        - name: "CONFIG_FORCE_akka_log__config__on__start"
          value: "off"

        #        - name: "CONFIG_FORCE_akka_cluster_role_frontend_min__nr__of__members"
        #          value: "1"

        - name: "CONFIG_FORCE_akka_cluster_sharding_number__of__shards"
          value: "30"

        - name: "CONFIG_FORCE_akka_management_http_bind__hostname"
          value: "0.0.0.0"
        - name: "CONFIG_FORCE_akka_management_http_bind__port"
          value: "8558"
        - name: "CONFIG_FORCE_akka_management_contract__point_fallback__ports"
          value: "8558"
      ingress:
        enabled: true
        alb:
          scheme: internet-facing
    backend:
      enabled: true
      version: 0.2.6
      withFrontend:
        enabled: false
      image:
        repository: 234188972441.dkr.ecr.us-east-1.amazonaws.com/om2eep1k-ecr-adceet-write-api-server-scala
        tag: dev-d3df642aea3a1f9c4052d095807b0273d20b3097-1661487120398
        pullPolicy: IfNotPresent
      resources:
        limits:
          cpu: "1"
          memory: "2Gi"
        requests:
          cpu: "0.5"
          memory: "1Gi"
      replicaCount: 3
      autoscaling:
        enabled: false
      processTimeoutInSec: 10
      serviceAccount:
        create: true
        name: write-api-server-backend-akka
      command:
        - /opt/docker/bin/adceet-write-api-server-scala
        - -Dconfig.resource=application-cluster-backend.conf
        - -Dconfig.override_with_env_vars=true
      env:
        - name: "CONFIG_FORCE_kamon_environment_tags_version"
          value: "adceet-write-api-server"

        - name: "CONFIG_FORCE_akka_log__config__on__start"
          value: "off"

        - name: "CONFIG_FORCE_akka_cluster_sharding_number__of__shards"
          value: "30"

        - name: "CONFIG_FORCE_akka_management_http_bind__hostname"
          value: "0.0.0.0"
        - name: "CONFIG_FORCE_akka_management_http_bind__port"
          value: "8558"
        - name: "CONFIG_FORCE_akka_management_contract__point_fallback__ports"
          value: "8558"

        - name: "CONFIG_FORCE_j5ik2o_dynamo__db__journal_table__name"
          value: "om2eep1k-Journal"
        - name: "CONFIG_FORCE_j5ik2o_dynamo__db__journal_get__journal__rows__index__name"
          value: "om2eep1k-GetJournalRowsIndex"
        - name: "CONFIG_FORCE_j5ik2o_dynamo__db__journal_shard__count"
          value: "64"
        - name: "CONFIG_FORCE_j5ik2o_dynamo__db__journal_queue__enable"
          value: "true"
        - name: "CONFIG_FORCE_j5ik2o_dynamo__db__journal_queue__buffer__size"
          value: "64"
        - name: "CONFIG_FORCE_j5ik2o_dynamo__db__journal_queue__overflow__strategy"
          value: "Fail"
        - name: "CONFIG_FORCE_j5ik2o_dynamo__db__journal_queue__parallelism"
          value: "1024"
        - name: "CONFIG_FORCE_j5ik2o_dynamo__db__journal_write__parallelism"
          value: "1024"
        - name: "CONFIG_FORCE_j5ik2o_dynamo__db__journal_query__batch__size"
          value: "32"
        - name: "CONFIG_FORCE_j5ik2o_dynamo__db__journal_scan__batch__size"
          value: "512"
        - name: "CONFIG_FORCE_j5ik2o_dynamo__db__journal_replay__batch__size"
          value: "512"

        - name: "CONFIG_FORCE_j5ik2o_dynamo__db__journal_consistent__read"
          value: "false"

        - name: "CONFIG_FORCE_j5ik2o_dynamo__db__snapshot_table__name"
          value: "om2eep1k-Snapshot"
        - name: "CONFIG_FORCE_j5ik2o_dynamo__db__snapshot_get__snapshot__rows__index__name"
          value: "om2eep1k-GetSnapshotRowsIndex"
        - name: "CONFIG_FORCE_j5ik2o_dynamo__db__snapshot_shard__count"
          value: "64"

        - name: "CONFIG_FORCE_cluster__dispatcher_fork__join__executor_parallelism__min"
          value: "4"
        - name: "CONFIG_FORCE_cluster__dispatcher_fork__join__executor_parallelism__max"
          value: "16"
        - name: "CONFIG_FORCE_cluster__dispatcher_fork__join__executor_parallelism__factor"
          value: "2.0"
