version: '3.6'
services:
  write-api-server-1:
    image: adceet-write-api-server-${MODE}
    container_name: write-api-server-1
    entrypoint: ["/opt/docker/bin/adceet-write-api-server-${MODE}", "-e", "development"]
    ports:
      - 18080:8081
      - 8558:8558
    environment:
      AWS_REGION: ap-northeast-1
      CONFIG_RESOURCE: application.conf
      AKKA_MANAGEMENT_HTTP_HOSTNAME: write-api-server-1
      AKKA_MANAGEMENT_HTTP_PORT: 8558
      AKKA_DISCOVERY_CONFIG_SERVICES_KAMON_EXAMPLE_ENDPOINTS_HOST1: write-api-server-1
      AKKA_DISCOVERY_CONFIG_SERVICES_KAMON_EXAMPLE_ENDPOINTS_HOST2: write-api-server-2
      AKKA_DISCOVERY_CONFIG_SERVICES_KAMON_EXAMPLE_ENDPOINTS_HOST3: write-api-server-3
      JVM_HEAP_MIN: 1G
      JVM_HEAP_MAX: 1G
      JVM_META_MAX: 512M
      J5IK2O_DYNAMO_DB_JOURNAL_DYNAMO_DB_CLIENT_ACCESS_KEY_ID: x
      J5IK2O_DYNAMO_DB_JOURNAL_DYNAMO_DB_CLIENT_SECRET_ACCESS_KEY: x
      J5IK2O_DYNAMO_DB_JOURNAL_DYNAMO_DB_CLIENT_ENDPOINT: http://dynamodb-local:8000
      J5IK2O_DYNAMO_DB_SNAPSHOT_DYNAMO_DB_CLIENT_ACCESS_KEY_ID: x
      J5IK2O_DYNAMO_DB_SNAPSHOT_DYNAMO_DB_CLIENT_SECRET_ACCESS_KEY: x
      J5IK2O_DYNAMO_DB_SNAPSHOT_DYNAMO_DB_CLIENT_ENDPOINT: http://dynamodb-local:8000
      J5IK2O_DYNAMO_DB_JOURNAL_TABLE_NAME: Journal
      J5IK2O_DYNAMO_DB_JOURNAL_GET_JOURNAL_ROWS_INDEX_NAME: GetJournalRowsIndex
      J5IK2O_DYNAMO_DB_SNAPSHOT_TABLE_NAME: Snapshot
    depends_on:
      - dynamodb-local
      - dynamodb-admin
      - dynamodb-setup
  write-api-server-2:
    image: adceet-write-api-server-${MODE}
    container_name: write-api-server-2
    entrypoint: ["/opt/docker/bin/adceet-write-api-server-${MODE}", "-e", "development"]
    ports:
      - 18081:8081
      - 8559:8559
    environment:
      AWS_REGION: ap-northeast-1
      CONFIG_RESOURCE: application.conf
      AKKA_MANAGEMENT_HTTP_HOSTNAME: write-api-server-2
      AKKA_MANAGEMENT_HTTP_PORT: 8559
      AKKA_DISCOVERY_CONFIG_SERVICES_KAMON_EXAMPLE_ENDPOINTS_HOST1: write-api-server-1
      AKKA_DISCOVERY_CONFIG_SERVICES_KAMON_EXAMPLE_ENDPOINTS_HOST2: write-api-server-2
      AKKA_DISCOVERY_CONFIG_SERVICES_KAMON_EXAMPLE_ENDPOINTS_HOST3: write-api-server-3
      JVM_HEAP_MIN: 1G
      JVM_HEAP_MAX: 1G
      JVM_META_MAX: 512M
      J5IK2O_DYNAMO_DB_JOURNAL_DYNAMO_DB_CLIENT_ACCESS_KEY_ID: x
      J5IK2O_DYNAMO_DB_JOURNAL_DYNAMO_DB_CLIENT_SECRET_ACCESS_KEY: x
      J5IK2O_DYNAMO_DB_JOURNAL_DYNAMO_DB_CLIENT_ENDPOINT: http://dynamodb-local:8000
      J5IK2O_DYNAMO_DB_SNAPSHOT_DYNAMO_DB_CLIENT_ACCESS_KEY_ID: x
      J5IK2O_DYNAMO_DB_SNAPSHOT_DYNAMO_DB_CLIENT_SECRET_ACCESS_KEY: x
      J5IK2O_DYNAMO_DB_SNAPSHOT_DYNAMO_DB_CLIENT_ENDPOINT: http://dynamodb-local:8000
      J5IK2O_DYNAMO_DB_JOURNAL_TABLE_NAME: Journal
      J5IK2O_DYNAMO_DB_JOURNAL_GET_JOURNAL_ROWS_INDEX_NAME: GetJournalRowsIndex
      J5IK2O_DYNAMO_DB_SNAPSHOT_TABLE_NAME: Snapshot
    depends_on:
      - dynamodb-local
      - dynamodb-admin
      - dynamodb-setup
      - write-api-server-1
  write-api-server-3:
    image: adceet-write-api-server-${MODE}
    container_name: write-api-server-3
    entrypoint: ["/opt/docker/bin/adceet-write-api-server-${MODE}", "-e", "development"]
    ports:
      - 18082:8081
      - 8560:8560
    environment:
      AWS_REGION: ap-northeast-1
      CONFIG_RESOURCE: application.conf
      AKKA_MANAGEMENT_HTTP_HOSTNAME: write-api-server-3
      AKKA_MANAGEMENT_HTTP_PORT: 8560
      AKKA_DISCOVERY_CONFIG_SERVICES_KAMON_EXAMPLE_ENDPOINTS_HOST1: write-api-server-1
      AKKA_DISCOVERY_CONFIG_SERVICES_KAMON_EXAMPLE_ENDPOINTS_HOST2: write-api-server-2
      AKKA_DISCOVERY_CONFIG_SERVICES_KAMON_EXAMPLE_ENDPOINTS_HOST3: write-api-server-3
      JVM_HEAP_MIN: 1G
      JVM_HEAP_MAX: 1G
      JVM_META_MAX: 512M
      J5IK2O_DYNAMO_DB_JOURNAL_DYNAMO_DB_CLIENT_ACCESS_KEY_ID: x
      J5IK2O_DYNAMO_DB_JOURNAL_DYNAMO_DB_CLIENT_SECRET_ACCESS_KEY: x
      J5IK2O_DYNAMO_DB_JOURNAL_DYNAMO_DB_CLIENT_ENDPOINT: http://dynamodb-local:8000
      J5IK2O_DYNAMO_DB_SNAPSHOT_DYNAMO_DB_CLIENT_ACCESS_KEY_ID: x
      J5IK2O_DYNAMO_DB_SNAPSHOT_DYNAMO_DB_CLIENT_SECRET_ACCESS_KEY: x
      J5IK2O_DYNAMO_DB_SNAPSHOT_DYNAMO_DB_CLIENT_ENDPOINT: http://dynamodb-local:8000
      J5IK2O_DYNAMO_DB_JOURNAL_TABLE_NAME: Journal
      J5IK2O_DYNAMO_DB_JOURNAL_GET_JOURNAL_ROWS_INDEX_NAME: GetJournalRowsIndex
      J5IK2O_DYNAMO_DB_SNAPSHOT_TABLE_NAME: Snapshot
    depends_on:
      - dynamodb-local
      - dynamodb-admin
      - dynamodb-setup
      - write-api-server-2