---
environments:
  {{ .Environment.Name }}:
    values:
      - environments/{{ .Environment.Name }}-values.yaml
releases:
  - name: adceet-write-api-server
    namespace: adceet
    chart: ../../charts/akka
    values:
      - values.yaml